### ISSUE TITLE
March MMP Run

### ISSUE THREAD

**Issue by Josh-The-Miner** [Mining-Store/MiningStore#113]

**Comment by warrenmining** [comment]
https://drive.google.com/drive/folders/1S9xr-RtvOZX4pgDZH-N7JUJpW1S1ewIB?usp=sharing

https://docs.google.com/spreadsheets/d/1Hhy74u_w_deZ2TS8ovzsVGcHjOPNM4SLkRPEJ36BB88/edit#gid=0
