### ISSUE TITLE
Find Intern

### ISSUE THREAD

**Issue by Josh-The-Miner** [Mining-Store/MiningStore#114]

**Comment by warrenmining** [comment]
Premasish Manna selected as PE Intern 1: https://trello.com/c/N24OusI1

**Comment by warrenmining** [comment]
Premasish's offer letter has been delivered. I have a feeling he is playing the field and may still reject the offer. It may be wise to offer an undergraduate intern as a plan B. 

In retrospect, I should have put a deadline on the unofficial offer, recognizing that I could offer plenty of other interns as well. Giving him the weekend to consider or something. If he doesn't accept by Friday, we may have to move to an undergraduate option.

**Comment by warrenmining** [comment]
Premasish accepted the offer. Closing issue. Will work with HR when necessary to help onboard.
